### ISSUE TITLE
Wine/Proton not starting simshmbridge.exe

### ISSUE THREAD

**Issue by NLRevZ** [Spacefreak18/simshmbridge#2]
Something seems to be going awry when I attempt to run Assetto Corsa Competizione with the custom command.
I compiled everything and created the directory structure you've used in your example which puts simshmbridge.exe under my ~/shmwrap/ac/ location. However, nothing seemed to happen when trying to run the game with the added launch command.
(I did start ./createsimshm in a terminal session)

When trying it manually, running the command yields the following:

```
user@machine:~/shmwrap$ protontricks --no-runtime --background-wineserver -c "wine ~/shmwrap/ac/simshmbridge.exe" 805550
wine: using kernel write watches, use_kernel_writewatch 1.
wine: failed to open "/home/user/shmwrap/ac/simshmbridge.exe": c0000135
```

I have given the entire _shmwrap_ folder and all of its subfolders and contents full read and write permissions to see if that might've been the issue but sadly, no change.

Running Fedora 40 (Nobara), if that makes any difference to the issue.

I'm doing something wrong here, it's just not clear to me what it is that I should be doing differently.

EDIT: If I look in the File Explorer under the prefix using protontricks, I can't see _shmwrap_ in the home folder. If I move it to the Documents subfolder of my home folder I can see it, however if I modify the path to reflect this change still nothing happens. Running it manually now seems to actually run _simshmbridge.exe_ but it stops on the following message: 
```
Could not find any OVR SHM objects: is service running?
```

Of course, I did run _createsimshm_ before executing this, and the same happens with or without ACC running at the time of executing these commands.

**Comment by NLRevZ** [comment]
I just discovered how to make it run: 
To even be able to play the game, I run it using GE-Proton9-11. Hence, I tried changing the Steam Proton launch command to `%command% & sleep 5 && ~/.local/share/Steam/compatibilitytools.d/GE-Proton9-11/proton run ~/Documents/shmwrap/ac/simshmbridge.exe` and now it starts fine.

Now I still need to figure out how to get the data through Monocoque to output RPM readings to my Moza wheel's RPM lightbar, but that's a different issue entirely and outside of the scope of this specific application..

**Comment by Spacefreak18** [comment]
yeah, i'm sorry the documentation was confusing, these days, i use a script which starts multiple tmux tabs, and one of them runs createsimshm, a tab for monocoque, etc, and then i run basically the launch command you have.

As for your larger issue, come join us if you have the time in the matrix chat.
https://matrix.to/#/#simracing:matrix.org

The guys that wrote boxflat and the driver for moza are there. @Lawstorant is working on support for moza to monocoque [fork](https://github.com/Lawstorant/monocoque).

I can certainly help, i've already added support for Cammus wheels to monocoque with the help of a member who has the hardware. I'm happy to keep adding wheels, we have the data ( if we don't it's just a matter of mapping it) after that it's just a matter of using the data to decide what bits to blast, and knowing where to blast them.
